spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order-microservice
    username: postgres
    password: peru2020
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 3007
