spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product-microservice
    username: postgres
    password: peru2020
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 3006

