spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory-microservice
    password: peru2020
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 3008
